networks:
  proxy:
    external: true

services:
  mdwp:
    build: .
    container_name: mdwp
    hostname: mdwp
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: ${SECRET_KEY}
    env_file:
      - .env
    networks:
      - proxy
