networks:
  proxy:
    external: true

services:
  mdwp:
    build: .
    container_name: mdwp
    hostname: mdwp
    volumes:
      - ./static_prod:/app/static_prod # Map the static folder to your host
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
    env_file:
      - .env
    networks:
      - proxy
